package com.linker.common;

public enum MessageType {
    ANY, GENERAL_ERROR, AUTH_REQUIRED,
    USER_CONNECTED, USER_DISCONNECTED,
    AUTH_CLIENT, AUTH_CLIENT_REPLY,
    AUTH_MASTER, AUTH_MASTER_REPLY,
    INVALID_MESSAGE, MESSAGE,
    MESSAGE_STATE_CHANGED,
    FETCH_MISSING_MESSAGES_REQUEST, FETCH_MISSING_MESSAGES_COMPLETE
}
